---
title: "Pre-QUES"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pre-QUES}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(LUMENSR)
library(magrittr)
library(dplyr)
library(purrr)
library(networkD3)
library(terra)
library(sf)
```

# 1. Data yang digunakan

```{r}

NTT_LC90 <- LUMENSR_example("NTT_LC90.tif") %>%
									 terra::rast() %>%
									 add_legend_to_categorical_raster(
									 raster_file = .,
									 lookup_table = lc_lookup_klhk_sequence)

plot_categorical_raster(NTT_LC90)
```

```{r}

NTT_LC20 <- LUMENSR_example("NTT_LC20.tif") %>%
									 terra::rast() %>%
									 add_legend_to_categorical_raster(
									 raster_file = .,
									 lookup_table = lc_lookup_klhk_sequence)

plot_categorical_raster(NTT_LC20)
```

```{r}
ggplot() +
  geom_sf(data = ntt_admin, fill = "lightblue", color = "black", size = 0.2) +
   ggrepel::geom_text_repel(
    data = ntt_admin,
    aes(label = Kabupaten, geometry = geometry),
    stat = "sf_coordinates",
    color = "grey30",     # text color
    bg.color = "white", # shadow color
    bg.r = 0.15 ,
    box.padding = 2,
    force = 1,
    max.overlaps = Inf) +      # shadow radius) +
  theme_minimal() +
  labs(
    title = "Map of NTT Administrative Areas",
    caption = "Source: Data Source"
  )

```

## Tabel deskripsi singkatan

```{r}
tabel_singkatan <- lc_lookup_klhk_sequence %>% 
  abbreviate_lookup() %>%
  dplyr::select(-color_pallette)

print(tabel_singkatan)
```

# 2. Hasil analisis pada tingkat bentang lahan

## Alur perubahan lahan dominan

```{r}
raster_files <- c("NTT_LC90.tif", "NTT_LC20.tif") %>%
    map(LUMENSR_example) %>%
    map(rast)

# Loop through raster files
raster_list <- 
  map(raster_files, ~apply_lookup_table(raster_file = .x, lookup_lc = lc_lookup_klhk_sequence))

# Turn raster files into a frequency table
crosstab_result <- create_crosstab(raster_list)
```

### Kondisi tutupan lahan keseluruhan

```{r}
# Input
create_sankey(freq_table = crosstab_result, area_cutoff = 10000, change_only = FALSE)
```

### Potret perubahan tutupan lahan

Tanpa mempertimbangkan tutupan lahan yang tidak berubah/ tetap.

```{r}
create_sankey(freq_table = crosstab_result, area_cutoff = 10000, change_only = TRUE)
```

## 10 jenis perubahan dominan

### Dalam Tabel

```{r}
luc_top_10 <- crosstab_result %>% 
 mutate_if(is.factor, as.character) %>%
      rowwise() %>%
      filter(n_distinct(c_across(-length(crosstab_result))) > 1) %>%
      ungroup() %>% 
      top_n(10)

print_frequency_table(luc_top_10)
```

### Dalam grafik

```{r}
library(stringr)
library(viridis)
library(scales)
library(ggplot2)
library(viridis)

# Get all column names except "Freq"
non_freq_cols <- colnames(luc_top_10)[!colnames(luc_top_10) %in% "Freq"]

# Create a new combined label by concatenating all other columns
luc_top_10$label <- apply(luc_top_10[non_freq_cols], 1, paste, collapse = " to ")

# Wrap the text to a maximum width of 20 characters
luc_top_10$label <- str_wrap(luc_top_10$label, width = 5)

# Plot the data
ggplot(luc_top_10, aes(x=reorder(label, Freq), y=Freq, fill=Freq)) +
  geom_bar(stat="identity") +
  coord_flip() +
  labs(x="Land Cover Change", y="Frequency", 
       #title="Frequency of Land Cover Change", 
       fill="Frequency") +
  theme_minimal() +
  scale_y_continuous(labels = comma) +
  scale_fill_viridis(discrete = FALSE, direction = -1, guide = "none", labels = comma)

```

# Hasil analisis pada unit perencanaan
